project_id    = "rich-clarke-dev"
region        = "europe-west2"
repository_id = "core-images"
service_name  = "portfolio_website"
image_name    = "europe-west2-docker.pkg.dev/rich-clarke-dev/core-images/portfolio_website:latest" 