name: Build and Deploy to Cloud Run

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  PROJECT_ID: your-project-id    # Replace with your GCP project ID
  REGION: europe-west2          # Replace with your preferred region
  SERVICE_NAME: portfolio       # Replace with your service name
  REGISTRY: europe-west2-docker.pkg.dev/${{ env.PROJECT_ID }}/portfolio

jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/123456789/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-provider'  # Replace with your provider
          service_account: 'github-actions@your-project-id.iam.gserviceaccount.com'  # Replace with your SA

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Configure Docker
        run: |
          gcloud auth configure-docker europe-west2-docker.pkg.dev --quiet

      - name: Build and Push Container
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ env.SERVICE_NAME }}:${{ github.sha }} .
          docker push ${{ env.REGISTRY }}/${{ env.SERVICE_NAME }}:${{ github.sha }}

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: ${{ env.SERVICE_NAME }}
          region: ${{ env.REGION }}
          image: ${{ env.REGISTRY }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
          flags: '--allow-unauthenticated' 
